### ISSUE TITLE
Consider loading of sqlite extension on startup. (or `load_extension` statements in macro)

### ISSUE THREAD

**Issue by copongcopong** [proofrock/sqliterg#2]
Consider allowing `load_extension` statements in `macro`. 

The purpose is the load sqlite extensions `onStartup: true`

**Comment by proofrock** [comment]
Thanks! Will do.

**Comment by proofrock** [comment]
From the discord thread:

> add the `load_extension` feature to the rusqlite row in Cargo.toml and compile it

**Comment by proofrock** [comment]
Should be done in v0.18.0. Please test, if you can.
