### ISSUE TITLE
How to run multiple `CREATE TABLE` statements in one transaction?

### ISSUE THREAD

**Issue by thanhnguyen2187** [proofrock/sqliterg#4]
Hi!

I'm trying to wrap Drizzle's around sqliterg. It works well if there is only one statement involved in one sqliterg transaction. However, if there are multiple statements, only the first one gets executed. For example, I have this SQL migration file that is generated by Drizzle:

```sql
CREATE TABLE `folders` (
	...
);
--> statement-breakpoint
CREATE TABLE `snippet_tags` (
	...
);
--> statement-breakpoint
CREATE TABLE `snippets` (
	...
);
```

Then only `CREATE TABLE folders` gets executed. What do you think I should do in this case? Must I parse the SQL myself and split it to multiple transaction before passing it to sqliterg?

Thanks!

**Comment by thanhnguyen2187** [comment]
For more context, I'm wrapping Drizzle around sqliterg like this:

```ts
export function createSqlitergExecutor(
  url: string,
  username: string,
  password: string,
): SqlitergExecutor {
  const authBase64 = Buffer.from(`${username}:${password}`).toString('base64')
  async function send(request: Request): Promise<Response> {
    const response = await fetch(
      url,
      {
        method: 'POST',
        headers: {
          // We need this to make testing works, as `fetch` of Vite would use
          // `Accept-Encoding: br, gzip, deflate`. It conflicts with the HTTP
          // server used by `sqliterg`, and make the underlying function unable
          // to decode the response.
          'Accept-Encoding': '*',
          'Content-Type': 'application/json',
          'Authorization': `Basic ${authBase64}`,
        },
        body: JSON.stringify(request)
      },
    )
    return response.json()
  }
  return {
    async isReachable(): Promise<boolean> {...},
    async isAuthenticated(): Promise<boolean> {...},
    async execute(queryOrStatement: string, params: Params | any[]): Promise<Response> {
      const queryOrStatementLowered = queryOrStatement.toLowerCase()
      let request: Request = {
        transaction: [],
      }

      if (
        queryOrStatementLowered.startsWith('select') ||
        queryOrStatementLowered.startsWith('pragma')
      ) {
        const transaction: Transaction = {
          query: queryOrStatement,
          values: params,
        }
        request.transaction.push(transaction)
      } else {
        const transaction: Transaction = {
          statement: queryOrStatement,
          values: params,
        }
        request.transaction.push(transaction)
      }

      return await send(request)
    }
  }
}

export async function createRemoteDb(executor: SqlitergExecutor) {
  return drizzle(async (queryString, params, method) => {
    const response = await executor.execute(queryString, params)
    if (response.results.length === 0 || !response.results[0].success) {
      return {rows: []}
    }
    const result = response.results[0]
    // @ts-ignore
    const records = result['resultSet'] as any[]
    if (records) {
      const values = records.map(Object.values)
      if (method === 'get' && values.length > 0) {
        return {rows: values[0]}
      }
      return {rows: values}
    }
    return {rows: []}
  })
}
```

You can take a look at my PR for the typing as well: https://github.com/thanhnguyen2187/crypta/pull/38

**Comment by proofrock** [comment]
Hi Thanh,
     nice work! Actually, sqliterg is a sort of thin wrapper around the most used "driver" for sqlite in the rust field, `rusqlite`. So, it supports things the way `rusqlite` supports them... and it doesn't support multiple statements, that I know of. Actually, in a kinda "fox and grape" way, I quite agree with this; supporting multiple statements would mean:

- somewhere you must parse the sql to split it, dealing with things like `-- ...`, `/* ... */`, `'...'` and such. This creates corner cases to deal with, and may be quite confusing;
- you still have to decide which resultset or value you should return;
- if you have parameters, they may be "spread" among different statements;
- the "multiple statement" must be in a transaction, and you have to ensure that an error properly rolls back all the possible previous sub-statements;

...and certainly many other aspects. It does also violate the fact that `sqliterg` names "queries" and "statements", and while this really is just a way to say "returns a resultset or a single value" (see `RETURNING`), I still don't like to allow to mix queries and statements in a single node.

So, I wouldn't like to go that way. If `rusqlite` supported it, I would take it and "pass through" so to speak. But I don't think adding a layer on top of `rusqlite` for this is desirable.

Thanks!

     G.

**Comment by thanhnguyen2187** [comment]
Many thanks for your detailed answer!

Within the wrapper, I toyed around splitting the input statement into smaller statements just using semi-colons (`;`) but I realized one problem you mentioned: how do I divide the parameters to the correct smaller statements? Therefore, in the end, I implemented the splitting to my migration code.

```ts
export async function migrate(
  db: SqliteRemoteDatabase,
  stateStore: Writable<MigrationState>,
  dataImportFn: (db: SqliteRemoteDatabase) => Promise<void>,
  migrationQueryMap: MigrationQueryMap,
  queriesStringMap: QueriesStringMap,
) {
  stateStore.set('running')
  let [currentUserVersion] = await db.get<[number]>(sql`PRAGMA user_version`)
  while (migrationQueryMap[currentUserVersion]) {
    const migrationQueryPath = migrationQueryMap[currentUserVersion]
    const migrationQueryString = queriesStringMap[migrationQueryPath]
    if (!migrationQueryString) {
      console.error(`migrate: could not find query string of ${migrationQueryPath}`)
      return
    }
    const statements = migrationQueryString.split(';').filter(statement => statement.length > 0)
    for (const statement of statements) {
      await db.run(sql.raw(statement))
    }
    if (currentUserVersion === 0) {
      try {
        await dataImportFn(db)
      }
      catch (e) {
        console.error('migrate: unable to import v0 data')
        console.error(e)
      }
      const path = '/db/0000_seed_default_folder.sql'
      const seedFolderQuery = queriesStringMap[path]
      await db.run(sql.raw(seedFolderQuery))
    }
    // TODO: investigate why using `?` within the query doesn't work
    currentUserVersion += 1
    await db.run(sql.raw(`PRAGMA user_version = ${currentUserVersion}`))
  }

  stateStore.set('done')
}
```

And it works well enough, as I can see the migration files myself and know how did it work.
